version: "3"

services:
  next-app:
    container_name: next-app
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    restart: always
    ports:
      - 3000:3000
    networks:
      - sms-network
    depends_on:
      - postgres

  # Add more containers below (nginx, postgres, etc.)
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    networks:
      - sms-network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  sms-network:
    driver: bridge
